add header responsive design and functions
TemuriTsutskiridze/Photosnap-Multipage-Website pull request #5
Opened 2023-04-19 21:53 UTC by MariamKvirchiladze

I wrote header design for all screen types, and also add functions for mobile version burger menu

2023-04-20 18:20 UTC, TemuriTsutskiridze requested changes

2023-04-21 22:50 UTC, MariamKvirchiladze commented
I corrected the position of header, and also add responsive designs of footer , and animations for header's burger menu.

2023-04-22 15:03 UTC, TemuriTsutskiridze requested changes

2023-04-22 20:07 UTC, MariamKvirchiladze commented
I tried to fix every problem I had in my code according your reviews.

2023-04-25 14:01 UTC, TemuriTsutskiridze approved these changes
Good Job

2023-04-25 14:01 UTC, merged